---
- hosts: all
  become: true
  tasks:
    - name: Install required package
      apt:
        pkg: "{{ item }}"
        state: present
        update-cache: yes
      become: yes
      with_items:
        - nfs-common

    - name: Mount Atlassian folders
      mount:
        src: "{{ nas_address }}:/{{ item }}"
        path: "/mnt/nas/{{ item.split('/')[-1] }}"
        fstype: nfs
        state: mounted
      with_items:
        - volume1/homes/confluence
        - volume1/homes/jira

    - name: Update Atlassian folder permissions
      file:
        path: "/mnt/nas/{{ item }}/application-data"
        state: directory
        owner: daemon
        group: daemon
      with_items:
        - confluence
        - jira

    # Container documentation from:
    # https://hub.docker.com/r/atlassian/confluence-server/
    # Equivalent docker call:
    # docker run 
    # -v /data/your-confluence-home:/var/atlassian/application-data/confluence
    # --name="confluence" -d -p 8090:8090 -p 8091:8091
    # atlassian/confluence-server

    - name: Add Confluence docker
      docker_container:
        name: confluence
        image: atlassian/confluence-server
        pull: true # Update the docker image
        network_mode: host
        volumes:
          - /mnt/nas/confluence/application-data:/var/atlassian/application-data/confluence
        ports:
          - "8090:8090"
          - "8091:8091"

    - name: Add Jira docker
      docker_container:
        name: jira
        image: cptactionhank/atlassian-jira
        pull: true
        network_mode: host
        volumes:
          - /mnt/nas/jira/application-data:/var/atlassian/jira
        ports:
          - "8080:8080"
