---
- hosts: all
  become: true
  tasks:
    - name: Install required package
      apt:
        pkg: "{{ item }}"
        state: present
        update-cache: yes
      become: yes
      with_items:
        - nfs-common

    - name: Mount shared folders
      mount:
        src: "{{ nas_address }}:/{{ item }}"
        path: "/mnt/nas/{{ item }}"
        fstype: nfs
        state: mounted
      with_items:
        - volume1/Series
        - volume1/Movies
        - volume1/StandUp
        - volume1/Formula 1
