---
- hosts: all
  become: true
  tasks:
    - name: Install required package
      apt:
        pkg: "{{ item }}"
        state: present
        update-cache: yes
      become: yes
      with_items:
        - nfs-common

    - name: Mount shared folders
      mount:
        src: "{{ nas_address }}:/{{ item }}"
        path: "/mnt/nas/{{ item }}"
        fstype: nfs
        state: mounted
      with_items:
        - volume1/Series
        - volume1/Movies
        - volume1/StandUp
        - volume1/Formula 1
        - volume1/Plex

    # Configuration documentation from https://github.com/plexinc/pms-docker
    - name: Add PMS docker.
      docker_container:
        name: plex
        image: plexinc/pms-docker
        pull: true # Update the docker
        network_mode: host
        restart_policy: always
        env:
          TZ: "{{ ansible_date_time.tz }}"
          PLEX_CLAIM: "{{ plex_claim_code }}"
          PLEX_UID: "{{ plex_uid }}"
          PLEX_GID: "{{ plex_gid }}"
        volumes:
          - /mnt/nas/volume1/Plex:/config
          - /mnt/nas/volume1:/volume1
          # Use the container's /transcode directory
        # Use this in the future
        # See https://github.com/ansible/ansible/pull/25747.
        # tmpfs:
        #   - /transcode:rw,exec
